# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-20 17:45
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='CensusTract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statefp', models.CharField(max_length=2)),
                ('countyfp', models.CharField(max_length=3)),
                ('tractce', models.CharField(max_length=6)),
                ('geoid', models.CharField(max_length=11)),
                ('name', models.CharField(max_length=7)),
                ('namelsad', models.CharField(max_length=20)),
                ('mtfcc', models.CharField(max_length=5)),
                ('funcstat', models.CharField(max_length=1)),
                ('aland', models.FloatField()),
                ('awater', models.FloatField()),
                ('intptlat', models.CharField(max_length=11)),
                ('intptlon', models.CharField(max_length=12)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4269)),
                ('income', models.PositiveIntegerField(null=True)),
                ('population', models.PositiveIntegerField(null=True)),
                ('no_eval_pts', models.PositiveSmallIntegerField(null=True)),
                ('pop_density', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Crime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4269)),
                ('occur_date', models.DateField()),
                ('category', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4269)),
                ('poly_pts', django.contrib.gis.db.models.fields.PolygonField(srid=4269)),
                ('favorability_score', models.FloatField()),
                ('ct_geoid', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4269)),
                ('price', models.CharField(max_length=6)),
                ('rating', models.FloatField()),
                ('categories', models.ManyToManyField(to='foodmap.Category')),
            ],
        ),
    ]
