# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-08 18:04
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='CensusTract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geo_id', models.CharField(max_length=60)),
                ('state', models.CharField(max_length=2)),
                ('county', models.CharField(max_length=3)),
                ('tract', models.CharField(max_length=6)),
                ('name', models.CharField(max_length=90)),
                ('lsad', models.CharField(max_length=7)),
                ('censusarea', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4269)),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('income_level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('price', models.CharField(max_length=6)),
                ('rating', models.FloatField()),
                ('categories', models.ManyToManyField(to='foodmap.Category')),
            ],
        ),
    ]
