# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-07 15:48
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodmap', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CensusTracts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geo_id', models.CharField(max_length=60)),
                ('state', models.CharField(max_length=2)),
                ('county', models.CharField(max_length=3)),
                ('tract', models.CharField(max_length=6)),
                ('name', models.CharField(max_length=90)),
                ('lsad', models.CharField(max_length=7)),
                ('censusarea', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4269)),
            ],
        ),
        migrations.DeleteModel(
            name='WorldBorder',
        ),
    ]
