# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 18:08
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodmap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationpoint',
            name='bigpoly_pts',
            field=django.contrib.gis.db.models.fields.PolygonField(null=True, srid=4269),
        ),
        migrations.AddField(
            model_name='evaluationpoint',
            name='crimecount',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='evaluationpoint',
            name='income',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='evaluationpoint',
            name='population',
            field=models.FloatField(null=True),
        ),
    ]
