# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-07 22:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodmap', '0002_auto_20161107_1548'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CensusTracts',
            new_name='CensusTract',
        ),
    ]
