# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodmap', '0002_auto_20161121_1808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluationpoint',
            name='crimecount',
        ),
        migrations.AddField(
            model_name='evaluationpoint',
            name='crime_count_local',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='evaluationpoint',
            name='crime_count_neighborhood',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
