# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 02:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodmap', '0002_censustract_income'),
    ]

    operations = [
        migrations.AddField(
            model_name='censustract',
            name='population',
            field=models.IntegerField(null=True),
        ),
    ]
