# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodmap', '0003_auto_20161121_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluationpoint',
            name='favorability_score',
            field=models.FloatField(default=0),
        ),
    ]
