# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-07 23:06
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodmap', '0003_auto_20161107_2233'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('price', models.PositiveSmallIntegerField()),
                ('rating', models.FloatField()),
                ('categories', models.ManyToManyField(to='foodmap.Category')),
            ],
        ),
    ]
