# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-07 23:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodmap', '0005_evaluationpoint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluationpoint',
            name='no_restaurants_nearby',
        ),
    ]
