# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodmap', '0005_restaurant_eval_pt_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationpoint',
            name='competitor_restaurant_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='evaluationpoint',
            name='partner_restaurant_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
