# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodmap', '0006_auto_20161130_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluationpoint',
            name='income',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='evaluationpoint',
            name='population',
            field=models.FloatField(default=0),
        ),
    ]
