# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-06 03:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodmap', '0008_evaluationpoint_favorability_percentile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluationpoint',
            name='crime_count_local',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='evaluationpoint',
            name='crime_count_neighborhood',
            field=models.FloatField(default=0),
        ),
    ]
